include: package:lint/strict.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    todo: info
    missing_required_param: error
    missing_return: error

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false
    omit_local_variable_types: true
    avoid_types_on_closure_parameters: true
    use_key_in_widget_constructors: true
    avoid_catching_errors: true
    avoid_catches_without_on_clauses: true
    unnecessary_lambdas: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_implementing_value_types: true
    use_setters_to_change_properties: false
    always_specify_types: false
